releases:
  - name: jira
    namespace: devops
    chart: ./atlassian-jira-software
    values:
      - ingress:
          enabled: true
          hosts:
            - jira.{{ requiredEnv "DEVOPS_DOMAIN" }}
        jira:
          javaHeapSize: 1536m
          reverseProxyHost: jira.{{ requiredEnv "DEVOPS_DOMAIN" }}
          # Disable websudo for SAML or OIDC
          javaOptions: "-Djira.websudo.is.disabled=true"
        resources:
          limits:
            # for single core CPU
            cpu: 800m
            memory: 2560Mi
          requests:
            cpu: 0
            memory: 2560Mi
