releases:
  - name: atlassian-jira-software
    namespace: devops
    chart: ./atlassian-jira-software
    values:
      - ingress:
          enabled: true
          hosts:
            - jira.example.com
        jira:
          reverseProxyHost: jira.example.com
        resources:
          limits:
            memory: 1536Mi
          requests:
            memory: 1536Mi
